--
-- PostgreSQL database dump
--

\restrict nuxgTDJSZruYlT0hTLre8UKEQ1mOcxKRYGTnfLLw5gcOIP6VMMeGqv2IHXrtWmB

-- Dumped from database version 18.3
-- Dumped by pg_dump version 18.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: rol; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE public.rol AS ENUM (
    '0',
    '1',
    '2',
    '3'
);


ALTER TYPE public.rol OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: tbl_cliente; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tbl_cliente (
    id_cel bigint NOT NULL,
    nombre character varying(50) NOT NULL,
    apellido character varying(50) NOT NULL,
    apodo character varying(30),
    direccion_c integer
);


ALTER TABLE public.tbl_cliente OWNER TO postgres;

--
-- Name: tbl_colonia; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tbl_colonia (
    idcolonia integer NOT NULL,
    colonia character varying(100) NOT NULL
);


ALTER TABLE public.tbl_colonia OWNER TO postgres;

--
-- Name: tbl_colonia_idcolonia_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tbl_colonia ALTER COLUMN idcolonia ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tbl_colonia_idcolonia_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tbl_corte; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tbl_corte (
    id_corte bigint NOT NULL,
    fecha date NOT NULL,
    total_ventas numeric(10,4) NOT NULL,
    total_gasto numeric(10,4) NOT NULL,
    ganancia numeric(10,4) NOT NULL
);


ALTER TABLE public.tbl_corte OWNER TO postgres;

--
-- Name: tbl_corte_id_corte_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tbl_corte ALTER COLUMN id_corte ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tbl_corte_id_corte_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tbl_det_gasto; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tbl_det_gasto (
    id_gasto_d bigint NOT NULL,
    monto numeric(10,4) NOT NULL,
    fecha date NOT NULL,
    id_gasto bigint NOT NULL,
    id_corte bigint
);


ALTER TABLE public.tbl_det_gasto OWNER TO postgres;

--
-- Name: tbl_det_gasto_id_gasto_d_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tbl_det_gasto ALTER COLUMN id_gasto_d ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tbl_det_gasto_id_gasto_d_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tbl_detalle_ventas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tbl_detalle_ventas (
    id_detalle_venta integer NOT NULL,
    cantidad integer NOT NULL,
    importe_p numeric(10,4) NOT NULL,
    nventa bigint,
    idprod character varying(30)
);


ALTER TABLE public.tbl_detalle_ventas OWNER TO postgres;

--
-- Name: tbl_detalle_ventas_id_detalle_venta_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.tbl_detalle_ventas_id_detalle_venta_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.tbl_detalle_ventas_id_detalle_venta_seq OWNER TO postgres;

--
-- Name: tbl_detalle_ventas_id_detalle_venta_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.tbl_detalle_ventas_id_detalle_venta_seq OWNED BY public.tbl_detalle_ventas.id_detalle_venta;


--
-- Name: tbl_direccion; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tbl_direccion (
    id_direc integer NOT NULL,
    num_casa character varying(45),
    calle character varying(45) NOT NULL,
    cruzamientos character varying(45) NOT NULL,
    referencia character varying(200) NOT NULL,
    colonia_d integer NOT NULL
);


ALTER TABLE public.tbl_direccion OWNER TO postgres;

--
-- Name: tbl_direccion_id_direc_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tbl_direccion ALTER COLUMN id_direc ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tbl_direccion_id_direc_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tbl_estado; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tbl_estado (
    id_estado character varying(10) NOT NULL,
    tipo_estado character varying(45) NOT NULL
);


ALTER TABLE public.tbl_estado OWNER TO postgres;

--
-- Name: tbl_fecha; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tbl_fecha (
    id_fecha date NOT NULL,
    dia character varying(2) NOT NULL,
    mes character varying(2) NOT NULL,
    anio character varying(4) NOT NULL
);


ALTER TABLE public.tbl_fecha OWNER TO postgres;

--
-- Name: tbl_gasto; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tbl_gasto (
    id_gasto bigint NOT NULL,
    descripcion character varying(255) NOT NULL
);


ALTER TABLE public.tbl_gasto OWNER TO postgres;

--
-- Name: tbl_gasto_id_gasto_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tbl_gasto ALTER COLUMN id_gasto ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tbl_gasto_id_gasto_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tbl_pago; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tbl_pago (
    id_pago character varying(2) NOT NULL,
    tipo_pago character varying(45) NOT NULL
);


ALTER TABLE public.tbl_pago OWNER TO postgres;

--
-- Name: tbl_producto; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tbl_producto (
    id_producto character varying(30) NOT NULL,
    nombre character varying(100) NOT NULL,
    cantidad numeric(10,4) NOT NULL,
    precio numeric(10,4) NOT NULL,
    estado boolean DEFAULT true
);


ALTER TABLE public.tbl_producto OWNER TO postgres;

--
-- Name: tbl_usuario; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tbl_usuario (
    id bigint NOT NULL,
    nombre character varying(50) NOT NULL,
    password character varying(250) NOT NULL,
    tipo public.rol NOT NULL,
    secion character varying(50) NOT NULL,
    estado character varying(50) NOT NULL
);


ALTER TABLE public.tbl_usuario OWNER TO postgres;

--
-- Name: tbl_venta; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tbl_venta (
    id_venta bigint NOT NULL,
    cantidad numeric(10,4) NOT NULL,
    importe_g numeric(10,4) NOT NULL,
    fecha date,
    num_cel bigint,
    tipo_pago character varying(2),
    tipo_estado character varying(10),
    id_corte bigint,
    id_usuario bigint NOT NULL
);


ALTER TABLE public.tbl_venta OWNER TO postgres;

--
-- Name: tbl_venta_id_venta_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tbl_venta ALTER COLUMN id_venta ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tbl_venta_id_venta_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tbl_detalle_ventas id_detalle_venta; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tbl_detalle_ventas ALTER COLUMN id_detalle_venta SET DEFAULT nextval('public.tbl_detalle_ventas_id_detalle_venta_seq'::regclass);


--
-- Data for Name: tbl_cliente; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tbl_cliente (id_cel, nombre, apellido, apodo, direccion_c) FROM stdin;
\.


--
-- Data for Name: tbl_colonia; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tbl_colonia (idcolonia, colonia) FROM stdin;
\.


--
-- Data for Name: tbl_corte; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tbl_corte (id_corte, fecha, total_ventas, total_gasto, ganancia) FROM stdin;
\.


--
-- Data for Name: tbl_det_gasto; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tbl_det_gasto (id_gasto_d, monto, fecha, id_gasto, id_corte) FROM stdin;
\.


--
-- Data for Name: tbl_detalle_ventas; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tbl_detalle_ventas (id_detalle_venta, cantidad, importe_p, nventa, idprod) FROM stdin;
\.


--
-- Data for Name: tbl_direccion; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tbl_direccion (id_direc, num_casa, calle, cruzamientos, referencia, colonia_d) FROM stdin;
\.


--
-- Data for Name: tbl_estado; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tbl_estado (id_estado, tipo_estado) FROM stdin;
\.


--
-- Data for Name: tbl_fecha; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tbl_fecha (id_fecha, dia, mes, anio) FROM stdin;
\.


--
-- Data for Name: tbl_gasto; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tbl_gasto (id_gasto, descripcion) FROM stdin;
\.


--
-- Data for Name: tbl_pago; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tbl_pago (id_pago, tipo_pago) FROM stdin;
\.


--
-- Data for Name: tbl_producto; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tbl_producto (id_producto, nombre, cantidad, precio, estado) FROM stdin;
\.


--
-- Data for Name: tbl_usuario; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tbl_usuario (id, nombre, password, tipo, secion, estado) FROM stdin;
\.


--
-- Data for Name: tbl_venta; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tbl_venta (id_venta, cantidad, importe_g, fecha, num_cel, tipo_pago, tipo_estado, id_corte, id_usuario) FROM stdin;
\.


--
-- Name: tbl_colonia_idcolonia_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tbl_colonia_idcolonia_seq', 1, false);


--
-- Name: tbl_corte_id_corte_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tbl_corte_id_corte_seq', 1, false);


--
-- Name: tbl_det_gasto_id_gasto_d_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tbl_det_gasto_id_gasto_d_seq', 1, false);


--
-- Name: tbl_detalle_ventas_id_detalle_venta_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tbl_detalle_ventas_id_detalle_venta_seq', 1, false);


--
-- Name: tbl_direccion_id_direc_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tbl_direccion_id_direc_seq', 1, false);


--
-- Name: tbl_gasto_id_gasto_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tbl_gasto_id_gasto_seq', 1, false);


--
-- Name: tbl_venta_id_venta_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tbl_venta_id_venta_seq', 1, false);


--
-- Name: tbl_cliente tbl_cliente_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tbl_cliente
    ADD CONSTRAINT tbl_cliente_pkey PRIMARY KEY (id_cel);


--
-- Name: tbl_colonia tbl_colonia_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tbl_colonia
    ADD CONSTRAINT tbl_colonia_pkey PRIMARY KEY (idcolonia);


--
-- Name: tbl_corte tbl_corte_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tbl_corte
    ADD CONSTRAINT tbl_corte_pkey PRIMARY KEY (id_corte);


--
-- Name: tbl_det_gasto tbl_det_gasto_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tbl_det_gasto
    ADD CONSTRAINT tbl_det_gasto_pkey PRIMARY KEY (id_gasto_d);


--
-- Name: tbl_detalle_ventas tbl_detalle_ventas_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tbl_detalle_ventas
    ADD CONSTRAINT tbl_detalle_ventas_pkey PRIMARY KEY (id_detalle_venta);


--
-- Name: tbl_direccion tbl_direccion_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tbl_direccion
    ADD CONSTRAINT tbl_direccion_pkey PRIMARY KEY (id_direc);


--
-- Name: tbl_estado tbl_estado_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tbl_estado
    ADD CONSTRAINT tbl_estado_pkey PRIMARY KEY (id_estado);


--
-- Name: tbl_fecha tbl_fecha_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tbl_fecha
    ADD CONSTRAINT tbl_fecha_pkey PRIMARY KEY (id_fecha);


--
-- Name: tbl_gasto tbl_gasto_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tbl_gasto
    ADD CONSTRAINT tbl_gasto_pkey PRIMARY KEY (id_gasto);


--
-- Name: tbl_pago tbl_pago_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tbl_pago
    ADD CONSTRAINT tbl_pago_pkey PRIMARY KEY (id_pago);


--
-- Name: tbl_producto tbl_producto_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tbl_producto
    ADD CONSTRAINT tbl_producto_pkey PRIMARY KEY (id_producto);


--
-- Name: tbl_usuario tbl_usuario_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tbl_usuario
    ADD CONSTRAINT tbl_usuario_pkey PRIMARY KEY (id);


--
-- Name: tbl_venta tbl_venta_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tbl_venta
    ADD CONSTRAINT tbl_venta_pkey PRIMARY KEY (id_venta);


--
-- Name: tbl_cliente tbl_cliente_direccion_c_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tbl_cliente
    ADD CONSTRAINT tbl_cliente_direccion_c_fkey FOREIGN KEY (direccion_c) REFERENCES public.tbl_direccion(id_direc);


--
-- Name: tbl_det_gasto tbl_det_gasto_id_corte_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tbl_det_gasto
    ADD CONSTRAINT tbl_det_gasto_id_corte_fkey FOREIGN KEY (id_corte) REFERENCES public.tbl_corte(id_corte);


--
-- Name: tbl_det_gasto tbl_det_gasto_id_gasto_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tbl_det_gasto
    ADD CONSTRAINT tbl_det_gasto_id_gasto_fkey FOREIGN KEY (id_gasto) REFERENCES public.tbl_gasto(id_gasto);


--
-- Name: tbl_detalle_ventas tbl_detalle_ventas_idprod_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tbl_detalle_ventas
    ADD CONSTRAINT tbl_detalle_ventas_idprod_fkey FOREIGN KEY (idprod) REFERENCES public.tbl_producto(id_producto);


--
-- Name: tbl_detalle_ventas tbl_detalle_ventas_nventa_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tbl_detalle_ventas
    ADD CONSTRAINT tbl_detalle_ventas_nventa_fkey FOREIGN KEY (nventa) REFERENCES public.tbl_venta(id_venta);


--
-- Name: tbl_direccion tbl_direccion_colonia_d_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tbl_direccion
    ADD CONSTRAINT tbl_direccion_colonia_d_fkey FOREIGN KEY (colonia_d) REFERENCES public.tbl_colonia(idcolonia);


--
-- Name: tbl_venta tbl_venta_fecha_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tbl_venta
    ADD CONSTRAINT tbl_venta_fecha_fkey FOREIGN KEY (fecha) REFERENCES public.tbl_fecha(id_fecha);


--
-- Name: tbl_venta tbl_venta_id_corte_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tbl_venta
    ADD CONSTRAINT tbl_venta_id_corte_fkey FOREIGN KEY (id_corte) REFERENCES public.tbl_corte(id_corte);


--
-- Name: tbl_venta tbl_venta_id_usuario_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tbl_venta
    ADD CONSTRAINT tbl_venta_id_usuario_fkey FOREIGN KEY (id_usuario) REFERENCES public.tbl_usuario(id);


--
-- Name: tbl_venta tbl_venta_num_cel_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tbl_venta
    ADD CONSTRAINT tbl_venta_num_cel_fkey FOREIGN KEY (num_cel) REFERENCES public.tbl_cliente(id_cel);


--
-- Name: tbl_venta tbl_venta_tipo_estado_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tbl_venta
    ADD CONSTRAINT tbl_venta_tipo_estado_fkey FOREIGN KEY (tipo_estado) REFERENCES public.tbl_estado(id_estado);


--
-- Name: tbl_venta tbl_venta_tipo_pago_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tbl_venta
    ADD CONSTRAINT tbl_venta_tipo_pago_fkey FOREIGN KEY (tipo_pago) REFERENCES public.tbl_pago(id_pago);


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: pg_database_owner
--

GRANT USAGE ON SCHEMA public TO lectura;
GRANT USAGE ON SCHEMA public TO admin;
GRANT USAGE ON SCHEMA public TO crud;


--
-- Name: TABLE tbl_cliente; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT ON TABLE public.tbl_cliente TO lectura;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.tbl_cliente TO admin;
GRANT SELECT,INSERT,UPDATE ON TABLE public.tbl_cliente TO crud;


--
-- Name: TABLE tbl_colonia; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT ON TABLE public.tbl_colonia TO lectura;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.tbl_colonia TO admin;
GRANT SELECT,INSERT,UPDATE ON TABLE public.tbl_colonia TO crud;


--
-- Name: SEQUENCE tbl_colonia_idcolonia_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT ON SEQUENCE public.tbl_colonia_idcolonia_seq TO lectura;
GRANT ALL ON SEQUENCE public.tbl_colonia_idcolonia_seq TO admin;
GRANT USAGE ON SEQUENCE public.tbl_colonia_idcolonia_seq TO crud;


--
-- Name: TABLE tbl_corte; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT ON TABLE public.tbl_corte TO lectura;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.tbl_corte TO admin;
GRANT SELECT,INSERT,UPDATE ON TABLE public.tbl_corte TO crud;


--
-- Name: SEQUENCE tbl_corte_id_corte_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT ON SEQUENCE public.tbl_corte_id_corte_seq TO lectura;
GRANT ALL ON SEQUENCE public.tbl_corte_id_corte_seq TO admin;
GRANT USAGE ON SEQUENCE public.tbl_corte_id_corte_seq TO crud;


--
-- Name: TABLE tbl_det_gasto; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT ON TABLE public.tbl_det_gasto TO lectura;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.tbl_det_gasto TO admin;
GRANT SELECT,INSERT,UPDATE ON TABLE public.tbl_det_gasto TO crud;


--
-- Name: SEQUENCE tbl_det_gasto_id_gasto_d_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT ON SEQUENCE public.tbl_det_gasto_id_gasto_d_seq TO lectura;
GRANT ALL ON SEQUENCE public.tbl_det_gasto_id_gasto_d_seq TO admin;
GRANT USAGE ON SEQUENCE public.tbl_det_gasto_id_gasto_d_seq TO crud;


--
-- Name: TABLE tbl_detalle_ventas; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT ON TABLE public.tbl_detalle_ventas TO lectura;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.tbl_detalle_ventas TO admin;
GRANT SELECT,INSERT,UPDATE ON TABLE public.tbl_detalle_ventas TO crud;


--
-- Name: SEQUENCE tbl_detalle_ventas_id_detalle_venta_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT ON SEQUENCE public.tbl_detalle_ventas_id_detalle_venta_seq TO lectura;
GRANT ALL ON SEQUENCE public.tbl_detalle_ventas_id_detalle_venta_seq TO admin;
GRANT USAGE ON SEQUENCE public.tbl_detalle_ventas_id_detalle_venta_seq TO crud;


--
-- Name: TABLE tbl_direccion; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT ON TABLE public.tbl_direccion TO lectura;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.tbl_direccion TO admin;
GRANT SELECT,INSERT,UPDATE ON TABLE public.tbl_direccion TO crud;


--
-- Name: SEQUENCE tbl_direccion_id_direc_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT ON SEQUENCE public.tbl_direccion_id_direc_seq TO lectura;
GRANT ALL ON SEQUENCE public.tbl_direccion_id_direc_seq TO admin;
GRANT USAGE ON SEQUENCE public.tbl_direccion_id_direc_seq TO crud;


--
-- Name: TABLE tbl_estado; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT ON TABLE public.tbl_estado TO lectura;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.tbl_estado TO admin;
GRANT SELECT,INSERT,UPDATE ON TABLE public.tbl_estado TO crud;


--
-- Name: TABLE tbl_fecha; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT ON TABLE public.tbl_fecha TO lectura;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.tbl_fecha TO admin;
GRANT SELECT,INSERT,UPDATE ON TABLE public.tbl_fecha TO crud;


--
-- Name: TABLE tbl_gasto; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT ON TABLE public.tbl_gasto TO lectura;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.tbl_gasto TO admin;
GRANT SELECT,INSERT,UPDATE ON TABLE public.tbl_gasto TO crud;


--
-- Name: SEQUENCE tbl_gasto_id_gasto_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT ON SEQUENCE public.tbl_gasto_id_gasto_seq TO lectura;
GRANT ALL ON SEQUENCE public.tbl_gasto_id_gasto_seq TO admin;
GRANT USAGE ON SEQUENCE public.tbl_gasto_id_gasto_seq TO crud;


--
-- Name: TABLE tbl_pago; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT ON TABLE public.tbl_pago TO lectura;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.tbl_pago TO admin;
GRANT SELECT,INSERT,UPDATE ON TABLE public.tbl_pago TO crud;


--
-- Name: TABLE tbl_producto; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT ON TABLE public.tbl_producto TO lectura;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.tbl_producto TO admin;
GRANT SELECT,INSERT,UPDATE ON TABLE public.tbl_producto TO crud;


--
-- Name: TABLE tbl_usuario; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT ON TABLE public.tbl_usuario TO lectura;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.tbl_usuario TO admin;
GRANT SELECT,INSERT,UPDATE ON TABLE public.tbl_usuario TO crud;


--
-- Name: TABLE tbl_venta; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT ON TABLE public.tbl_venta TO lectura;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.tbl_venta TO admin;
GRANT SELECT,INSERT,UPDATE ON TABLE public.tbl_venta TO crud;


--
-- Name: SEQUENCE tbl_venta_id_venta_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT ON SEQUENCE public.tbl_venta_id_venta_seq TO lectura;
GRANT ALL ON SEQUENCE public.tbl_venta_id_venta_seq TO admin;
GRANT USAGE ON SEQUENCE public.tbl_venta_id_venta_seq TO crud;


--
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO admin;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT USAGE ON SEQUENCES TO crud;


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT ON TABLES TO lectura;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT,INSERT,DELETE,UPDATE ON TABLES TO admin;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT,INSERT,UPDATE ON TABLES TO crud;


--
-- PostgreSQL database dump complete
--

\unrestrict nuxgTDJSZruYlT0hTLre8UKEQ1mOcxKRYGTnfLLw5gcOIP6VMMeGqv2IHXrtWmB

